### ISSUE TITLE
Web framework

### ISSUE THREAD

**Issue by meizuflux** [MrKomodoDragon/animal-api#1]
This project is using Quart, an async version of flask. An API is more suited to the capabilities of FastAPI. Therefor, I suggest you change over to fastapi

**Comment by MrKomodoDragon** [comment]
We is using fastapi now 🙂
________________________________
From: ppotatoo ***@***.***>
Sent: Tuesday, July 13, 2021 5:28 PM
To: MrKomodoDragon/animal-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MrKomodoDragon/animal-api] Web framework (#1)


This project is using Quart, an async version of flask. An API is more suited to the capabilities of FastAPI. Therefor, I suggest you change over to fastapi

**Comment by meizuflux** [comment]
uh no you arent
